// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbinojczqtlizhxpuqdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4YW1vYXphc2Z6bWtveXhseXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTM0MTcsImV4cCI6MjA2Nzc2OTQxN30.DCdTYU4ePyTizIewfOEjrHE0haFzOEf92TRLbKzkHgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});