// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dycglwkkfchnlzszkgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Y2dsd2trZmNobmx6c3prZ3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTQ4OTMsImV4cCI6MjA2NzkzMDg5M30.oFvuNmIhieMRn-O5SrvWaLaLjoTmvDjoylfIJwy2-YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});